# kenyan_names.py

# A raw list of names including nicknames, celebrities, and politicians
_RAW_NAMES = [
    "mwangi", "kamau", "njoki", "wanjiru", "mutua",
    "dee", "diana d", "captain morgan", "brian",
    "otieno", "akinyi", "kiptoo", "kibet", "chebet","Salet","onjiri"
    "kartelo", "harrison", "wanyama", "matiangi",
    "ruto", "odinga", "dorea", "obinna", "janet",
    "jackson", "patrick osio", "oppina", "sabrina",
    "pamela", "captain", "hannah", "jesus",
    "stevo simple boy", "culture", "patero",
    "kenya", "awoh", "mary", "ivano", "hana",
    "mc exodus", "brina", "masha", "bobo actress",
    "bull's family", "pastor nga'ng'a",
    "diana luvunda", "samir", "freddie oxygen",
    "oga", "mr t", "kinuthia", "jeff koinange",
    "obama", "king kalala", "obizze",
    "baba lola", "nancy", "azziad nasenya",
    "dicky sleek", "mr mbilimbili",
    "kalija beibe", "mitchelle joyce",
    "mbote njogu", "ombachi dennis",
    "corazon kwamboka", "baby rue",
    "emmanuel chiche", "milly chebby",
    "finess ngara", "joy kendi",
    "bernice nunah", "richy haniel",
    "the wajesus family", "tt comedian",
    "urban street", "otile brown",
    "njugush", "elsa majimbo",
    "chief safro", "kakan maiyo",
    "ethic entertainment", "reckless",
    "swat", "seska", "ziko",
    "sailors gang", "miracle baby",
    "masauti", "maringo", "boondocks gang",
    "ozy manda", "exray", "maddox",
    "benzema", "matata", "mejja",
    "madtraxx", "boutross",
    "breeder lw", "trio mio",
    "nviiri the storyteller",
    "bahati", "mulla mtoto",
    "khaligraph jones", "octopizzo",
    "ssaru", "femi one", "maandy",
    "domani munga", "the kansoul",
    "vigro deep", "buruklyn boyz",
    "xtian dela", "akothee",
    "diana marua", "tanasha donna",
    "willy paul", "eric omondi",
    "andrew kibe", "miguna miguna",
    "babu owino", "uhuru kenyatta",
    "william ruto", "raila odinga",
    "martha karua", "david ndii",
    "mutahi ngunyi", "jebet koech",
    "pluto", "thee pluto",
    "terry", "quavo", "lanos",
    "iano", "angeline gesare",
    "jammo", "naira", "akoth",
    "domani mkadinali", "denno dartelo",
    "ianoh", "wakorino", "pasta",
    "mario", "sandra", "tesla",
    "ibra", "fellah", "maasai",
    "masai", "teslah", "kiara",
    "alma", "kimeu", "alma omg",
    "mutheu", "jakeem", "kadha",
    "mercya", "wambui", "stinyo",
    "abuto's", "flava", "mr right",
    "lyricali", "toxic lyricali",
    "manat", "remix", "pelzy",
    "ot4", "kecobo", "kharligraph jone",
    "vj patelo", "patello", "kadhi", "mnisa", 
    "toxic lyrikali", "toxic", "khaligraph", "lykali", "omondi", 
    "billgate", "onlyomoke", "mana t", "virusi mbaya", 
    "toxic x aress x omoke", "nrg", "torpedo", "elisha", 
    "esir", "denzel . n mnisa", "giftehk", "mana tttt", 
    "tox", "mnisaaaa", "skilibeng", "dossi g", "ares", "kiprop",
    "mana tox ic", "brad", "e-syde", "manna tox", "aruna", 
    "mr.t", "manner t.o.x", "warena", "d.c.lvlistening", "t.o.x"
]
# Generate a clean, unique, sorted list
KENYAN_NAMES = sorted(list(set([name.strip().lower() for name in _RAW_NAMES])))
